Add basic tests structure and travis
agamm/comeback pull request #37
Opened 2019-03-09 22:43 UTC by agamm

Do not approve yet.

2019-03-09 22:45 UTC, agamm commented
See https://travis-ci.org/agamm/comeback

2019-03-09 22:46 UTC, agamm commented
Add more tests so we are at least 50% covered then we will merge.
fixes https://github.com/agamm/comeback/issues/3

2019-03-20 18:44 UTC, yammesicka requested changes

2019-03-20 18:44 UTC, yammesicka commented on tests/utils_test.py
> +    if utils.get_platform() == "windows":
'

2019-03-20 18:44 UTC, yammesicka commented on tests/utils_test.py
> +    assert (utils.is_binary_exists('thisdoesntexistihope') is False)
You can remove the parenthesis from all the `assert` statements

2019-03-20 18:44 UTC, yammesicka commented on tests/utils_test.py
> +def test_report_issue():
I won't do it, looks to me like WET

2019-03-20 18:44 UTC, yammesicka commented on tests/utils_test.py
> +    commands = utils._format_command("")
Maybe we should make _format_command public?

Testing private methods is [a bit strange](https://stackoverflow.com/questions/105007/should-i-test-private-methods-or-only-public-ones)

2019-03-20 18:44 UTC, yammesicka commented on tests/test_helper.py
> +def create_directory(tmp_path, dirname=TEST_DIR):
Maybe we should use context manager here. We don't want to leave folders after the test has completed running.

2019-03-20 18:44 UTC, yammesicka commented on tests/test_helper.py
> +def create_test_file(tmp_path, text_content, file_name="test.txt"):
'

2019-03-20 18:44 UTC, yammesicka commented on tests/test_helper.py
> +    create_directory(tmp_path, "1")
'

2019-03-20 18:44 UTC, yammesicka commented on .gitignore
> +.pth
Add a blank line in the end of the file

2019-03-20 20:00 UTC, agamm commented on tests/utils_test.py
> +def test_report_issue():
I actually did that test to setup things, I don't see any harm in it being there... (protects the issue url could be a very small incentive, but it still is)

2019-03-20 20:01 UTC, agamm commented on tests/utils_test.py
> +    commands = utils._format_command("")
I like this comment, https://stackoverflow.com/a/105209/904992

2019-03-20 20:03 UTC, agamm commented on tests/test_helper.py
> +def create_directory(tmp_path, dirname=TEST_DIR):
"context manager"?

2019-03-22 22:54 UTC, agamm commented on tests/utils_test.py
> +    assert (utils.is_binary_exists('thisdoesntexistihope') is False)
I wanted it to feel like the py3 print...

2019-03-22 23:26 UTC, agamm commented
I'm happy to announce that we have passed the 50% coverage in our tests right now.
@yammesicka do you mind adding tests for `comeback\config.py` and `comeback\paths.py` please?

2019-03-23 16:13 UTC, yammesicka commented on tests/utils_test.py
> +def test_report_issue():
I see what you mean. We have a disagreement here, so I (asked the community)[https://softwareengineering.stackexchange.com/questions/389074/unittests-for-functions-that-only-prints-a-string], hope that's ok ^^"

My position is that the URL can still be changed, just in 2 places instead of 1. It just creates kind of coupling, 'cause if you want to change the message you'll also need to change the tests.

2019-03-23 16:13 UTC, yammesicka commented on tests/utils_test.py
> +    commands = utils._format_command("")
👍

2019-03-23 16:14 UTC, yammesicka commented on tests/test_helper.py
> +def create_directory(tmp_path, dirname=TEST_DIR):
`with ___ as ___:`, that will delete the file after using it

2019-03-23 16:17 UTC, yammesicka commented
> I'm happy to announce that we have passed the 50% coverage in our tests right now.
> @yammesicka do you mind adding tests for `comeback\config.py` and `comeback\paths.py` please?

Sure, it would just take some time 'cause I have the Python course which I have procrastinated for some long time.

2019-03-23 22:07 UTC, agamm commented on tests/utils_test.py
> +def test_report_issue():
I liked the no-shame plug of our project URL there :)
PS. I'll remove the test and add skip for coverage

2019-03-23 22:09 UTC, agamm commented on tests/test_helper.py
> +def create_directory(tmp_path, dirname=TEST_DIR):
Hmm, but shouldn't it be written in the test itself?

2019-03-23 22:10 UTC, agamm commented
> > I'm happy to announce that we have passed the 50% coverage in our tests right now.
> > @yammesicka do you mind adding tests for `comeback\config.py` and `comeback\paths.py` please?
> 
> Sure, it would just take some time 'cause I have the Python course which I have procrastinated for some long time.

Yeah we get it, take your time. Just remember that you are the one who can bring the green badge to us :)  
_(Also another badge for coverage(!))_

2019-04-06 22:02 UTC, agamm commented
@yammesicka Ok, I got to 65% cov. I think we can merge this if you accept the changes, so we could start having testing.

2019-04-07 19:47 UTC, yammesicka approved these changes

2019-04-07 19:47 UTC, yammesicka commented on comeback/main.py
> +    index = int(input("> ")) # pragma: no cover
Double space before `#`

2019-04-07 19:47 UTC, yammesicka commented on comeback/plugins/mock/main.py
> +def check_plugin(print: Optional[str] = None) -> utils.RUN_STATUS:
I'd use another name to prevent overriding the `print` function

2019-04-07 19:47 UTC, yammesicka commented on comeback/main.py
> +        click.echo("YAML Error: " + str(exc))
Use '

2019-04-07 19:47 UTC, yammesicka commented on tests/config_test.py
> +    pe = config.create_path_entity("test")
Use `'`

2019-04-07 19:47 UTC, yammesicka commented on tests/config_test.py
> +    pe = config.create_path_entity("test")
Name clarification: `pe`

2019-04-07 19:47 UTC, yammesicka commented on tests/config_test.py
> +        time.time())  # this may be undeterministic, consider removing
If an inline comment make you break line, put it above the commented line instead

2019-04-07 19:47 UTC, yammesicka commented on tests/config_test.py
> +    assert (pe == {'test': last_used})
Unnecessary parenthesis

2019-04-07 19:47 UTC, yammesicka commented on tests/main_test.py
> +    assert (result.exit_code == 0)
Remove parenthesis to all asserts

2019-04-07 19:47 UTC, yammesicka commented on tests/main_test.py
> +    assert ("expected str" in result.output)
Use ' instead of "

2019-04-07 19:47 UTC, yammesicka commented on tests/paths_test.py
> +    restore_env_xdg(dv, cv)
Add a new line

2019-04-07 21:33 UTC, agamm commented on tests/config_test.py
> +        time.time())  # this may be undeterministic, consider removing
pycharm

2019-04-07 21:33 UTC, agamm commented on tests/main_test.py
> +    assert (result.exit_code == 0)
fuck that, do that when you do tests man

2019-04-07 21:34 UTC, agamm commented on tests/main_test.py
> +    assert (result.exit_code == 0)
<3

2019-04-07 21:37 UTC, agamm commented on tests/main_test.py
> +    assert (result.exit_code == 0)
omg, fu, i did it `assert\s?\((.*?)\)$`

2019-04-07 21:39 UTC, agamm commented
Continue here: https://github.com/agamm/comeback/issues/43
We merged this because we want to start having basic tests, even if it isn't complete.

2019-04-07 21:50 UTC, merged